function [train_error, valid_error] =learningCurve(initialweights,input_layer_size,...
                                     hidden_layer1_size,hidden_layer2_size,no_labels,x, y, xval, yval, lambda,epochs)



m = size(xval, 1);

train_error = zeros(m, 1);
valid_error   = zeros(m, 1);





for i=1:m,
  [finalweights, costval] = training_model(initialweights, ...
                                         input_layer_size, ...
                                         hidden_layer1_size, ...
                                         hidden_layer2_size,no_labels, ...
                                         x((1:i),:), y(1:i), lambda,epochs);
  [Jtrain, gradtrain]=CostandGradient(finalweights, ...
                                     input_layer_size, ...
                                     hidden_layer1_size, ...
                                     hidden_layer2_size,no_labels, ...
                                     x((1:i),:), y(1:i), 0);
  [Jvalid, gradvalid]=CostandGradient(finalweights, ...
                                     input_layer_size, ...
                                     hidden_layer1_size, ...
                                     hidden_layer2_size,no_labels, ...
                                     xval, yval, 0);

  train_error(i)=Jtrain;
  valid_error(i)=Jvalid;

end

end
